spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 068890080ea538d86702
            clientSecret: 05b0a58674d4b85e180a143df9e8323e64c067ed
          google:
            clientId: 807000458878-3rhqqcvij9r6cg6i57q4tqtkuuq35nsv.apps.googleusercontent.com
            clientSecret: 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

